name: checkPackage

on:
  pull_request:
    branches: [main, master]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: "https://rse.pik-potsdam.de/r/packages"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            gamstransfer=?ignore
            any::lucode2
            any::covr
            any::madrat
            any::magclass
            any::citation
            any::gms
            any::goxygen
            any::GDPuc
          # piam packages also available on CRAN (madrat, magclass, citation,
          # gms, goxygen, GDPuc) will usually have an outdated binary version
          # available; by using extra-packages we get the newest version

      - name: Verify that lucode2::buildLibrary was successful
        shell: Rscript {0}
        run: lucode2:::isVersionUpdated()
